### ISSUE TITLE
Documentación: conceptos básicos de CFD

### ISSUE THREAD

**Issue by rsanfer** [catedra-corunet/tfg-bcibeira#2]
### Obxectivo

**Documentar** os conceptos básicos do dominio CFD (dinámica de fluidos computacional)
**que** se inclúen no listado de _información adicional_ desta tarefa
**para** facilitar a correcta comprensión do proxecto e a linguaxe dos usuarios

### Subtarefas
- [x] Buscar documentación referente ós diferentes conceptos
- [x] Elaborar un glosario de conceptos do dominio
- [x] Incluir as referencias (páxinas web, artigos) nas que se basa o glosario
- [x] Incluir, en todos os conceptos, o seu nome en inglés
- [x] Revisar o glosario con @rsanfer 

---

#### Listado de conceptos e palabras clave

- Fluido
- Presión
- Momento lineal
- Fluxo incompresible
- Velocidade do son
- Subsónico
- Supersónico
- Número de Mach
- Fluxo compresible
- Forzas aerodinámicas
- Sustentación
- Arrastre
- Perfil aerodinámico
- Viscosidade
- Rozamento viscoso
- Ecuacións de Euler
- Ecuacións de Navier Stokes
- Fluxo laminar
- Turbulencia
- Fluxo turbulento
- Número de Reynolds
- Modelo de turbulencia

#### Notas
- Os conceptos están ordeados segundo a orde na que deben ser traballados. 
- O contido do glosario debe ser de unha ou dúas frases en linguaxe natural, non técnico.
- **Non** se deben incluir ecuacións neste punto. 
- Non se pretende que as definicións sexan rigurosas nin física nin matemáticamente, senón fáciles de entender de xeito intuitivo.

**Comment by rsanfer** [comment]
Glosario revisado. Bótalle unha ollada, @brais999 , e cando o teñas revisado péchaa se tes dúbidas, ou comenta por aquí se non.

https://github.com/catedra-corunet/tfg-bcibeira/wiki/%5BDominio%5D-Glosario-de-conceptos/_compare/5d697d8f131aa9c039a4139d6e388dadbf542fd8...d19ac6779f20d16341890e35aed8ab137eb027ee

**Comment by brais999** [comment]
Revisada
