### ISSUE TITLE
Análise de alternativas: software de CFD

### ISSUE THREAD

**Issue by rsanfer** [catedra-corunet/tfg-bcibeira#3]
### Obxectivo

**Analizar** as alternativas existentes de software de CFD, xa sexan OSS ou comerciais
**que** existen no mercado 
**para** poder decidir o enfoque do proxecto, o público obxectivo e as carencias actuais detectadas

### Subtarefas
- [ ] Buscar os paquetes de software máis coñecidos
- [ ] Comprender o funcionamiento destes mediante videotutoriais ou documentación pública
- [ ] Definir cal é o fluxo de traballo máis habitual neste tipo de software
- [ ] Analizar os pros e contras destas alternativas 
- [ ] Establecer e comprender o actual posicionamento de mercado de SU2

**Comment by rsanfer** [comment]
[Revisión da documentación] (https://github.com/catedra-corunet/tfg-bcibeira/wiki/%5BDominio%5D-Ferramentas-CFD/_compare/1527d05aec54fc85e971961c7f752291d4520e21...31407ee965b7dc28b28891f84c3f65adf4a853aa)

De novo Brais, revisa e mañán charlamos na daily.

**Comment by brais999** [comment]
Revisado
